# Generated by Django 4.0.1 on 2022-05-11 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='is_correct',
            new_name='is_locked',
        ),
    ]
