# Generated by Django 4.0.1 on 2022-05-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='is_finished',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='is_started',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
