# Generated by Django 4.0.1 on 2022-04-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_exam_session_examquestion_exam_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='finish_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='start_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
