# Generated by Django 4.0.1 on 2022-05-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_session_is_finished_session_is_started'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('VERY EASY', 'VERY EASY'), ('EASY', 'EASY'), ('NORMAL', 'NORMAL'), ('DIFFICULT', 'DIFFICULT'), ('VERY DIFFICULT', 'VERY DIFFICULT')], default='NORMAL', max_length=100, null=True),
        ),
    ]
