# Generated by Django 4.0.1 on 2022-05-11 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='access',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.session'),
        ),
    ]
