# Generated by Django 4.0.1 on 2022-04-30 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_exam_matricola_exam_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='number_of_exams',
        ),
    ]
