# Generated by Django 4.0.4 on 2022-05-15 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_access_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='type',
        ),
    ]
