# Generated by Django 4.0.1 on 2022-05-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_session_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='weight_blank_answer',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='weight_correct_answer',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='weight_wrong_answer',
            field=models.IntegerField(null=True),
        ),
    ]
