# Generated by Django 4.0.4 on 2022-05-21 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_examquestion_answer_examanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sessions', models.IntegerField(blank=True, null=True)),
                ('not_started_sessions', models.IntegerField(blank=True, null=True)),
                ('started_sessions', models.IntegerField(blank=True, null=True)),
                ('finished_sessions', models.IntegerField(blank=True, null=True)),
                ('total_exams', models.IntegerField(blank=True, null=True)),
                ('started_exams', models.IntegerField(blank=True, null=True)),
                ('finished_exams', models.IntegerField(blank=True, null=True)),
                ('average_votation_exams_10', models.IntegerField(blank=True, null=True)),
                ('average_votation_exams_30', models.IntegerField(blank=True, null=True)),
                ('total_questions', models.IntegerField(blank=True, null=True)),
                ('correct_questions', models.IntegerField(blank=True, null=True)),
                ('blank_questions', models.IntegerField(blank=True, null=True)),
                ('wrong_questions', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='statistic',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.subjectstatistics'),
        ),
    ]
