# Generated by Django 4.0.1 on 2022-05-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_session_weight_blank_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='weight_blank_answer',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='weight_correct_answer',
            field=models.FloatField(default=3, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='weight_wrong_answer',
            field=models.FloatField(default=-1, null=True),
        ),
    ]
