# Generated by Django 4.0.4 on 2022-05-21 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_subjectstatistics_subject_statistic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='statistic',
            new_name='statistics',
        ),
    ]
